In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]),
 tensor([[119., 133.],
         [ 22.,  37.],
         [ 56.,  70.],
         [119., 133.],
         [ 22.,  37.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[-0.3879, -0.4304,  0.3922],
        [-0.2189, -0.2490, -0.5698]], requires_grad=True)
---------
Parameter containing:
tensor([-0.0044,  0.5062], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [11]:
# Define loss function
loss_fn = F.mse_loss

In [12]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(22877.4316, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [13]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [14]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(37.1367, grad_fn=<MseLossBackward>)


In [15]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.0482,  71.7960],
        [ 83.9512,  96.0745],
        [113.3484, 139.8448],
        [ 26.2983,  45.5296],
        [101.9072, 106.3604],
        [ 58.0482,  71.7960],
        [ 83.9512,  96.0745],
        [113.3484, 139.8448],
        [ 26.2983,  45.5296],
        [101.9072, 106.3604],
        [ 58.0482,  71.7960],
        [ 83.9512,  96.0745],
        [113.3484, 139.8448],
        [ 26.2983,  45.5296],
        [101.9072, 106.3604]], grad_fn=<AddmmBackward>)

In [16]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [17]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(15.8004, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [19]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.73266609 0.81397813 0.30146181]
 [0.57308328 0.02550587 0.82354316]]
Biases:
[[0.54271117 0.94240298]
 [0.60453688 0.9571017 ]
 [0.48019233 0.25695075]
 [0.11295721 0.00529217]
 [0.76333078 0.56001356]
 [0.01472286 0.99117333]
 [0.28973774 0.06966777]
 [0.49865902 0.91012109]
 [0.64505541 0.21941785]
 [0.29706507 0.53375311]
 [0.39398807 0.48498531]
 [0.24366418 0.38278502]
 [0.23025406 0.47921564]
 [0.36161226 0.58221162]
 [0.67273645 0.21190365]]


In [20]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [21]:

# Generate predictions
preds = model(inputs)

In [22]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[121.52672809  79.89873171]
 [158.20078209 108.05895919]
 [190.77999623 101.29848632]
 [121.00004485  90.02763599]
 [150.56151787 100.19934493]
 [120.99873978  79.94750206]
 [157.88598295 107.17152526]
 [190.79846291 101.95165665]
 [121.53214304  90.24176168]
 [150.09525215 100.17308448]
 [121.37800499  79.44131405]
 [157.83990939 107.48464251]
 [190.53005795 101.52075121]
 [121.24869989  90.60455545]
 [150.47092353  99.85123501]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [24]:
# Compute loss
loss = mse(preds, targets)
print(loss)

6350.315560321062


In [25]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[12561.35777172 11829.39441035  7552.83758461]
 [ 1083.16152017 -1000.72687131  -133.75502411]]
biases_grad:
[[ 8.73689708  1.31983089]
 [10.29343761  0.94119456]
 [ 9.57066616 -4.22686849]
 [13.20000598  7.07035147]
 [ 6.34153572 -2.50675401]
 [ 8.66649864  1.32633361]
 [10.25146439  0.82287003]
 [ 9.57312839 -4.13977911]
 [13.27095241  7.09890156]
 [ 6.27936695 -2.5102554 ]
 [ 8.71706733  1.25884187]
 [10.24532125  0.864619  ]
 [ 9.53734106 -4.19723317]
 [13.23315999  7.14727406]
 [ 6.32945647 -2.55316866]]


Adjust weights

In [26]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [27]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.60705251 0.69568418 0.22593343]
 [0.56225166 0.03551314 0.82488071]]
Biases:
[[0.5426238  0.94238978]
 [0.60443394 0.95709229]
 [0.48009663 0.25699302]
 [0.11282521 0.00522146]
 [0.76326736 0.56003863]
 [0.01463619 0.99116007]
 [0.28963522 0.06965954]
 [0.49856329 0.91016249]
 [0.6449227  0.21934687]
 [0.29700227 0.53377821]
 [0.3939009  0.48497273]
 [0.24356173 0.38277638]
 [0.23015868 0.47925762]
 [0.36147993 0.58214015]
 [0.67267315 0.21192918]]


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

3413.8850290907567


In [29]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

24.042988070753566


In [31]:
# Print predictions
print(preds)

[[ 58.25171712  71.55681747]
 [ 80.04430224 101.67736266]
 [122.56621035 130.14649672]
 [ 25.64971098  40.73691631]
 [ 95.41745479 117.7947015 ]
 [ 57.72387029  71.60557476]
 [ 79.72958746 100.79016652]
 [122.58467209 130.79949203]
 [ 26.18166659  40.95098462]
 [ 94.95131401 117.76844809]
 [ 58.10303387  71.09952238]
 [ 79.68352624 101.10319987]
 [122.31633905 130.36870205]
 [ 25.89829939  41.31368117]
 [ 95.32688473 117.44668487]]


In [32]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
