In [7]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [8]:
# Imports
import torch.nn as nn

In [9]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [10]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [13]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [14]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [15]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.]]),
 tensor([[119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [119., 133.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [16]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[ 0.1170, -0.2941,  0.1951],
        [-0.4804,  0.5391,  0.2710]], requires_grad=True)
---------
Parameter containing:
tensor([-0.2953,  0.4796], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [17]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [18]:
# Import nn.functional
import torch.nn.functional as F

In [19]:
# Define loss function
loss_fn = F.mse_loss

In [20]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(6797.1206, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [21]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [22]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(15.7089, grad_fn=<MseLossBackward>)


In [23]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.5743,  70.7386],
        [ 82.5244,  98.3602],
        [115.8410, 137.3545],
        [ 29.3875,  38.9138],
        [ 97.5574, 114.1189],
        [ 58.5743,  70.7386],
        [ 82.5244,  98.3602],
        [115.8410, 137.3545],
        [ 29.3875,  38.9138],
        [ 97.5574, 114.1189],
        [ 58.5743,  70.7386],
        [ 82.5244,  98.3602],
        [115.8410, 137.3545],
        [ 29.3875,  38.9138],
        [ 97.5574, 114.1189]], grad_fn=<AddmmBackward>)

In [24]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [25]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(4.0678, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [32]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [33]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.56215353 0.82506494 0.73905728]
 [0.7380137  0.65522779 0.00434456]]
Biases:
[[0.27291508 0.43003859]
 [0.91339983 0.39352099]
 [0.5019864  0.40621639]
 [0.63478372 0.43053909]
 [0.15011756 0.46775446]
 [0.00729053 0.92413002]
 [0.53350648 0.5888655 ]
 [0.2635151  0.44169426]
 [0.73235718 0.51819675]
 [0.38153501 0.41475428]
 [0.92411092 0.89504852]
 [0.09267903 0.57257184]
 [0.91841013 0.63412459]
 [0.00841077 0.74816245]
 [0.66890972 0.76455394]]


In [34]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [35]:

# Generate predictions
preds = model(inputs)

In [36]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[128.36893615  98.39211664]
 [171.97475086 125.49086495]
 [202.83336677 152.6659164 ]
 [120.79735485 104.0434803 ]
 [169.8789542  114.59668659]
 [128.10331159  98.88620807]
 [171.59485751 125.68620945]
 [202.59489547 152.70139426]
 [120.89492831 104.13113795]
 [170.11037166 114.5436864 ]
 [129.02013198  98.85712657]
 [171.15403006 125.66991579]
 [203.2497905  152.89382459]
 [120.17098191 104.36110365]
 [170.39774636 114.89348606]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [37]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [39]:
# Compute loss
loss = mse(preds, targets)
print(loss)

8216.555914683682


In [42]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[14209.8061901  13901.84106954  8851.17974795]
 [ 5043.42169671  3684.25186752  2455.51592872]]
biases_grad:
[[ 9.64919149  3.78561555]
 [12.12996678  3.26544866]
 [11.17778224  2.62212219]
 [13.17298065  8.93913071]
 [ 8.91719389 -0.58710845]
 [ 9.61377488  3.85149441]
 [12.07931433  3.29149459]
 [11.14598606  2.62685257]
 [13.18599044  8.95081839]
 [ 8.94804955 -0.59417515]
 [ 9.7360176   3.84761688]
 [12.02053734  3.2893221 ]
 [11.2333054   2.65250995]
 [13.08946425  8.98148049]
 [ 8.98636618 -0.54753519]]


Adjust weights

In [43]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [44]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[ 0.42005546  0.68604653  0.65054548]
 [ 0.68757949  0.61838527 -0.0202106 ]]
Biases:
[[0.27281859 0.43000073]
 [0.91327853 0.39348834]
 [0.50187462 0.40619017]
 [0.63465199 0.4304497 ]
 [0.15002839 0.46776033]
 [0.00719439 0.92409151]
 [0.53338568 0.58883258]
 [0.26340364 0.44166799]
 [0.73222532 0.51810724]
 [0.38144553 0.41476022]
 [0.92401356 0.89501004]
 [0.09255882 0.57253894]
 [0.9182978  0.63409806]
 [0.00827987 0.74807263]
 [0.66881986 0.76455941]]


In [45]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

3955.518847612338


In [46]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [47]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

51.43898386238415


In [48]:
# Print predictions
print(preds)

[[ 57.5795726   71.39364682]
 [ 82.24092856  96.20597994]
 [118.64878337 140.6091485 ]
 [ 24.2823307   42.90090513]
 [ 99.21221742 108.17033182]
 [ 57.31401923  71.88760586]
 [ 81.861137    96.4012721 ]
 [118.41037597 140.64461686]
 [ 24.37987802  42.9885393 ]
 [ 99.44357286 108.11734584]
 [ 58.23059394  71.85853215]
 [ 81.42042768  96.38498281]
 [119.06509552 140.83699562]
 [ 23.6561256   43.21844337]
 [ 99.73087057 108.46705177]]


In [50]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
